kind: Service
apiVersion: v1
metadata:
  name: appconfig-service
spec:
  selector:
    app: appconfig-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appconfig-service
spec:
  selector:
    matchLabels:
      app: appconfig-service
  replicas: 1
  template:
    metadata:
      labels:
        app: appconfig-service
    spec:
      containers:
        - name: appconfig-service
          image: appconfig-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080