kind: Service
apiVersion: v1
metadata:
  name: view-service
spec:
  selector:
    app: view-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-service
spec:
  selector:
    matchLabels:
      app: view-service
  replicas: 1
  template:
    metadata:
      labels:
        app: view-service
    spec:
      containers:
        - name: view-service
          image: view-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080